### ISSUE TITLE
CameraX crashed under Android 9

### ISSUE THREAD

**Issue by as564335sa** [Android-for-Python/c4k_photo_example#1]
Hi,
    All demos about camera4kivy crashed under Android 9,this the logcat:
```
--------- beginning of crash
06-15 23:38:12.577  4976  4976 E AndroidRuntime: FATAL EXCEPTION: main
06-15 23:38:12.577  4976  4976 E AndroidRuntime: Process: org.wheet.wheet, PID: 4976
06-15 23:38:12.577  4976  4976 E AndroidRuntime: java.lang.IllegalArgumentException: No supported surface combination is found for camera device - Id : 0.  May be attempting to bind too many use cases. Existing surfaces: [] New configs: [androidx.camera.core.impl.VideoCaptureConfig@9592f79, androidx.camera.core.impl.ImageCaptureConfig@80644be, androidx.camera.core.impl.PreviewConfig@7ac7440]
06-15 23:38:12.577  4976  4976 E AndroidRuntime: 	at androidx.camera.lifecycle.LifecycleCameraRepository.bindToLifecycleCamera(LifecycleCameraRepository.java:280)
06-15 23:38:12.577  4976  4976 E AndroidRuntime: 	at androidx.camera.lifecycle.ProcessCameraProvider.bindToLifecycle(ProcessCameraProvider.java:532)
06-15 23:38:12.577  4976  4976 E AndroidRuntime: 	at androidx.camera.lifecycle.ProcessCameraProvider.bindToLifecycle(ProcessCameraProvider.java:381)
06-15 23:38:12.577  4976  4976 E AndroidRuntime: 	at org.kivy.camerax.CameraX.bindPreview(CameraX.java:288)
06-15 23:38:12.577  4976  4976 E AndroidRuntime: 	at org.kivy.camerax.CameraX.configureCamera(CameraX.java:273)
06-15 23:38:12.577  4976  4976 E AndroidRuntime: 	at org.kivy.camerax.CameraX.access$100(CameraX.java:52)
06-15 23:38:12.577  4976  4976 E AndroidRuntime: 	at org.kivy.camerax.CameraX$1.run(CameraX.java:169)
06-15 23:38:12.577  4976  4976 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
06-15 23:38:12.577  4976  4976 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-15 23:38:12.577  4976  4976 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
06-15 23:38:12.577  4976  4976 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6678)
06-15 23:38:12.577  4976  4976 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-15 23:38:12.577  4976  4976 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:518)
06-15 23:38:12.577  4976  4976 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
06-15 23:38:12.580  3246  3461 W ActivityManager:   Force finishing activity org.wheet.wheet/org.kivy.android.PythonActivity
06-15 23:38:12.584  3246  3262 I ActivityManager: Showing crash dialog for package org.wheet.wheet u0
```
what's wrong?

**Comment by Android-for-Python** [comment]
The issue appears to be  `May be attempting to bind too many use cases. ` I don't know why.

I assume this is device related rather than Android version related. Is the device in this list ? https://developer.android.com/training/camerax/devices

My guess is the device has limited photo hardware resources, so if you want to, one thing to try:

By default c4k configures `connect_camera()` for either 'photo and video` or 'photo and image analysis' - this keeps api as simple as possible.  We can change this, for example by disabling the video functionality ('use case' in the jargon) for a particular camera connection. 

In the 'c4k_photo_example' https://github.com/Android-for-Python/c4k_photo_example/blob/main/applayout/photoscreen1.py#L26 change `connect_camera(filepath_callback= self.capture_path)` to `connect_camera(enable_video = False,filepath_callback= self.capture_path)`

The first screen only 'may' work (I'm not going to say 'should' because this is based on a guess).

**Comment by as564335sa** [comment]
Great, you're right! I set `enable_ video = false`, it works well, thank you！

**Comment by Android-for-Python** [comment]
Great, thanks for the feedback. I will update the documentation. Its nice when things work out easily.

If you are using `connect_camera()` to record video or do data analysis I expect you will need to instead set `connect_camera(enable_photo = False)`.
